# Generated by Django 4.0.3 on 2022-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CNT', 'CNT'), ('YEN', 'YEN'), ('AUD', 'AUD'), ('AED', 'AED'), ('SGD', 'SGD')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CNT', 'CNT'), ('YEN', 'YEN'), ('AUD', 'AUD'), ('AED', 'AED'), ('SGD', 'SGD')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CNT', 'CNT'), ('YEN', 'YEN'), ('AUD', 'AUD'), ('AED', 'AED'), ('SGD', 'SGD')], max_length=5, null=True),
        ),
    ]
