# Generated by Django 4.0.3 on 2022-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flight_currency_hotel_currency_package_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
